//! P10.16.5: QFM-TSR validation on 2D Kolmogorov-flow CFD snapshots.
//!
//! The 2D **Kolmogorov flow** is a canonical forced-turbulence test case
//! in computational fluid dynamics: the 2D incompressible Navier–Stokes
//! equation on a doubly-periodic box, forced by a single-mode
//! sinusoidal body force that pumps energy in at a fixed wavenumber
//! and lets viscosity $\nu$ remove it at the high-wavenumber tail.
//!
//! Governing equation (vorticity form, $\omega = \nabla \times \vec u$):
//!
//!   $\partial_t \omega = -\vec u \cdot \nabla \omega + \nu \nabla^2 \omega
//!                       + f(x, y)$
//!
//! with $f(x, y) = \sin(k_f x) \cos(k_f y)$ the Kolmogorov forcing,
//! $k_f = 4$, $\vec u = \nabla^\perp \psi$, $\nabla^2 \psi = -\omega$,
//! and $(x, y) \in [0, 2\pi)^2$ with periodic BCs.
//!
//! This is genuinely **different** from the CIFAR-10 / Ising cross-domain
//! tests:
//!
//!   * **Continuous PDE** with deterministic forcing + viscous decay
//!     (not a discrete spin flip or a labelled image).
//!   * **Long-range spatial correlations** generated by the inverse
//!     Laplacian $\psi = -\nabla^{-2}\omega$, the same operator that
//!     appears in the QFM-TSR pipeline's $W$ basis construction.
//!   * **Time-dependent** — the training set is a temporal trajectory
//!     through the state space, so successive snapshots are
//!     auto-correlated (and not IID, unlike MNIST/CIFAR).
//!
//! This makes the Kolmogorov flow a good stress test for the QFM-TSR
//! pipeline's ability to learn structured, spatially-correlated
//! distributions from real PDE-generated data.
//!
//! ## What the test verifies
//!
//! 1. The QFM-TSR pipeline compiles on d=256 (L=16) Kolmogorov-flow
//!    vorticity snapshots with the rank-truncation path
//!    (`max_rank=Some(16)`, `krylov_dim=32`, M=64 < K_2=256 forces
//!    the P10.16.3 lossy path, same setup as `ising2d_validation.rs`).
//! 2. `generate()` returns finite pixel values.
//! 3. Cosine similarity to the nearest training snapshot is positive.
//! 4. Quantum Bayesian update on a held-out snapshot runs end-to-end.
//!
//! ## Acceptance for P10.16.5
//!
//! `cargo test -p qfm --test cfd_kolmogorov_validation` runs clean and
//! the metrics are reported (not strict thresholds; this is the third
//! cross-domain QFM-TSR baseline, after 2D Ising and CIFAR-10).
//!
//! ## Numerical method
//!
//! A direct pseudospectral solver on a uniform $L \times L$ grid with
//! periodic BCs:
//!
//!   * Vorticity field $\omega$ in real space, $\hat\omega$ in Fourier.
//!   * Stream function $\hat\psi_k = \hat\omega_k / |k|^2$ (regularised
//!     to zero at $k=0$).
//!   * Velocity in Fourier: $\hat u_x = i k_y \hat\psi$, $\hat u_y = -i k_x \hat\psi$.
//!   * Nonlinear term $\widehat{\vec u \cdot \nabla\omega}$ via
//!     2/3-rule dealiasing (zero the top third of modes).
//!   * Forcing $\hat f$: precomputed analytically.
//!   * Time integration: classic 4th-order Runge–Kutta (RK4) on the
//!     Fourier coefficients. (The QFM-TSR test does not need ETDRK4's
//!     extra stability for the moderate $\nu$ we use; the explicit RK4
//!     is the simplest readable solver and lets the test stay in
//!     < 100 lines.)
//!
//! Determinism: the solver is fully deterministic from a fixed seed
//! (initial vorticity drawn from a Gaussian random field in Fourier
//! space). No external data, no JSON fixtures.

use qfm::{
    HmcOpts, Likelihood, Posterior, QfmConfig, QfmPipeline, sample_hmc_single, tsr_evolved_prior,
};

// ── Spectral helpers ────────────────────────────────────────────────────────

const L: usize = 16; // grid resolution per axis
const D: usize = L * L; // d = 256 pixels
const NU: f64 = 0.05; // viscosity (moderate; the test only
//   needs plausible-looking vortices,
//   not a faithful Reynolds-number study)
const KF: f64 = 4.0; // Kolmogorov forcing wavenumber
const DT: f64 = 0.01; // time step (stable for ν=0.05, L=16)

/// splitmix64 — matches the PRNG used throughout `qfm` for reproducibility.
fn splitmix64(x: u64) -> u64 {
    let x = x.wrapping_add(0x9e3779b97f4a7c15);
    let x = (x ^ (x >> 30)).wrapping_mul(0xbf58476d1ce4e5b9);
    let x = (x ^ (x >> 27)).wrapping_mul(0x94d049bb133111eb);
    x ^ (x >> 31)
}

/// 2/3-rule dealiasing mask: zero the top third of wavenumber magnitudes
/// in each direction. Returns a flat `Vec<bool>` indexed `(kx, ky)`.
fn dealias_mask() -> Vec<bool> {
    let cutoff = (2 * L / 3) as i32;
    let mut mask = vec![false; L * L];
    for kx in 0..L {
        for ky in 0..L {
            // Wrap the wavenumber to [-L/2, L/2).
            let kx_wrapped = if kx > L / 2 {
                kx as i32 - L as i32
            } else {
                kx as i32
            };
            let ky_wrapped = if ky > L / 2 {
                ky as i32 - L as i32
            } else {
                ky as i32
            };
            mask[kx * L + ky] = kx_wrapped.abs() < cutoff && ky_wrapped.abs() < cutoff;
        }
    }
    mask
}

/// Precompute the Kolmogorov forcing $\hat f(k_x, k_y)$ for the test.
/// $f(x, y) = \sin(k_f x) \cos(k_f y)$ on $[0, 2\pi)^2$. The Fourier
/// transform has support only at $\pm(k_f, \pm k_f)$ (with the
/// $\cos/\sin$ phase factors).
fn kolmogorov_forcing_hat() -> Vec<(f64, f64)> {
    let mut hat = vec![(0.0, 0.0); L * L];
    // $\hat f(k_x, k_y) = (1/4) \cdot i \cdot \mathrm{sgn}(k_x, k_y)$ at
    // the four $\pm k_f$ points. Compute the real + imaginary parts.
    let kf = KF as i32;
    // sin(kf x) cos(kf y) = (1/2)[sin(kf(x+y)) + sin(kf(x-y))]
    // so $\hat f$ has support at $\pm(k_f, k_f)$ and $\pm(k_f, -k_f)$.
    // Each is purely imaginary with magnitude 1/4 (for the (1/(2π)²
    // convention) or, equivalently under the unnormalized DFT used here,
    // 1/2 (one factor per quadrant). We use the unnormalized DFT: the
    // $L^2$ factor from the real-space sum and the $1/L^2$ from the
    // inverse DFT cancel, and the analytic values are $i/2$ or $-i/2$
    // depending on the quadrant.
    for &(sx, sy) in &[(1, 1), (1, -1), (-1, 1), (-1, -1)] {
        let kx_idx = ((kf * sx).rem_euclid(L as i32)) as usize;
        let ky_idx = ((kf * sy).rem_euclid(L as i32)) as usize;
        // Sign of the imaginary part depends on the quadrant.
        let sign = (sx * sy) as f64;
        // For the real-space function $f(x,y) = \sin(k_f x)\cos(k_f y)$,
        // the discrete Fourier transform gives
        //   $\hat f(k_x, k_y) = (L^2/4) \cdot (i) \cdot [\delta_{k_x,k_f}
        //     - \delta_{k_x,-k_f}] \cdot [\delta_{k_y,k_f} + \delta_{k_y,-k_f}]$
        // (from the trig identity), normalised so the inverse DFT recovers
        // $f(x, y)$ exactly on the discrete grid.
        let imag_part = sign * (L * L) as f64 / 4.0;
        hat[kx_idx * L + ky_idx] = (0.0, imag_part);
    }
    hat
}

/// Compute $|\vec k|^2$ (squared wavenumber magnitude) for each mode,
/// as a real `Vec<f64>`. The (0, 0) mode is set to 1.0 to avoid
/// division by zero when computing $\hat\psi = \hat\omega / |\vec k|^2$.
fn k_squared() -> Vec<f64> {
    let mut out = vec![1.0; L * L];
    for kx in 0..L {
        for ky in 0..L {
            let kx_wrapped = if kx > L / 2 {
                kx as i32 - L as i32
            } else {
                kx as i32
            };
            let ky_wrapped = if ky > L / 2 {
                ky as i32 - L as i32
            } else {
                ky as i32
            };
            out[kx * L + ky] = (kx_wrapped * kx_wrapped + ky_wrapped * ky_wrapped) as f64;
        }
    }
    out
}

/// 1D iterative Cooley–Tukey FFT (radix-2, in-place).
/// Length must be a power of 2.
fn fft1d_inplace(a: &mut [(f64, f64)], inverse: bool) {
    let n = a.len();
    debug_assert!(n.is_power_of_two(), "fft1d requires power-of-2 length");
    // Bit-reversal permutation.
    let mut j = 0;
    for i in 1..n {
        let mut bit = n >> 1;
        while j & bit != 0 {
            j ^= bit;
            bit >>= 1;
        }
        j ^= bit;
        if i < j {
            a.swap(i, j);
        }
    }
    // Butterflies.
    let sign = if inverse { 1.0 } else { -1.0 };
    let mut len = 2;
    while len <= n {
        let half = len / 2;
        let theta = sign * 2.0 * std::f64::consts::PI / (len as f64);
        let wlen = (theta.cos(), theta.sin());
        for i in (0..n).step_by(len) {
            let mut w = (1.0, 0.0);
            for k in 0..half {
                let (ur, ui) = a[i + k];
                let (vr, vi) = a[i + k + half];
                let tr = vr * w.0 - vi * w.1;
                let ti = vr * w.1 + vi * w.0;
                a[i + k] = (ur + tr, ui + ti);
                a[i + k + half] = (ur - tr, ui - ti);
                // Advance the twiddle: w *= wlen.
                let (wr, wi) = w;
                w = (wr * wlen.0 - wi * wlen.1, wr * wlen.1 + wi * wlen.0);
            }
        }
        len <<= 1;
    }
    if inverse {
        let scale = 1.0 / (n as f64);
        for x in a.iter_mut() {
            *x = (x.0 * scale, x.1 * scale);
        }
    }
}

/// 2D FFT via row-then-column 1D FFTs. The 2D output is in the same
/// row-major order as the input. `inverse=true` divides by `L*L`
/// (the inverse normaliser) so an inverse call undoes a forward call
/// up to numerical noise.
fn fft2d(x: &mut [(f64, f64)], inverse: bool) {
    // Row FFTs.
    for kx in 0..L {
        let mut row: Vec<(f64, f64)> = (0..L).map(|ky| x[kx * L + ky]).collect();
        fft1d_inplace(&mut row, inverse);
        for ky in 0..L {
            x[kx * L + ky] = row[ky];
        }
    }
    // Column FFTs.
    for ky in 0..L {
        let mut col: Vec<(f64, f64)> = (0..L).map(|kx| x[kx * L + ky]).collect();
        fft1d_inplace(&mut col, inverse);
        for kx in 0..L {
            x[kx * L + ky] = col[kx];
        }
    }
}

/// Forward 2D DFT: real input -> complex output (row-major).
fn dft2d(x: &[f64]) -> Vec<(f64, f64)> {
    let mut buf: Vec<(f64, f64)> = x.iter().map(|&v| (v, 0.0)).collect();
    fft2d(&mut buf, false);
    buf
}

/// Inverse 2D DFT: complex input (row-major) -> real output.
fn idft2d(x_hat: &[(f64, f64)]) -> Vec<f64> {
    let mut buf: Vec<(f64, f64)> = x_hat.to_vec();
    fft2d(&mut buf, true);
    buf.iter().map(|&(r, _)| r).collect()
}

/// Compute the nonlinear term $\widehat{\vec u \cdot \nabla\omega}$ in
/// Fourier space. Uses 2/3-rule dealiasing on the velocity and
/// vorticity-gradient products before the final transform.
fn nonlinear_term_hat(omega_hat: &[(f64, f64)], ksq: &[f64], mask: &[bool]) -> Vec<(f64, f64)> {
    // Stream function $\hat\psi_k = \hat\omega_k / |\vec k|^2$ (k != 0).
    let mut psi_hat = vec![(0.0, 0.0); L * L];
    for i in 0..L * L {
        if ksq[i] > 0.0 {
            let (wr, wi) = omega_hat[i];
            psi_hat[i] = (wr / ksq[i], wi / ksq[i]);
        }
    }
    // Velocity $\hat u_x = i k_y \hat\psi$, $\hat u_y = -i k_x \hat\psi$.
    let mut ux_hat = vec![(0.0, 0.0); L * L];
    let mut uy_hat = vec![(0.0, 0.0); L * L];
    for kx in 0..L {
        for ky in 0..L {
            let kx_wrapped = if kx > L / 2 {
                kx as i32 - L as i32
            } else {
                kx as i32
            };
            let ky_wrapped = if ky > L / 2 {
                ky as i32 - L as i32
            } else {
                ky as i32
            };
            let (pr, pi) = psi_hat[kx * L + ky];
            // $\hat u_x = i k_y \hat\psi = (-k_y \pi, k_y p_r)$.
            ux_hat[kx * L + ky] = (-(ky_wrapped as f64) * pi, (ky_wrapped as f64) * pr);
            // $\hat u_y = -i k_x \hat\psi = (k_x \pi, -k_x p_r)$.
            uy_hat[kx * L + ky] = ((kx_wrapped as f64) * pi, -(kx_wrapped as f64) * pr);
        }
    }
    // Vorticity gradient: $\widehat{\partial_x \omega} = i k_x \hat\omega$,
    // $\widehat{\partial_y \omega} = i k_y \hat\omega$.
    let mut dwdx_hat = vec![(0.0, 0.0); L * L];
    let mut dwdy_hat = vec![(0.0, 0.0); L * L];
    for kx in 0..L {
        for ky in 0..L {
            let kx_wrapped = if kx > L / 2 {
                kx as i32 - L as i32
            } else {
                kx as i32
            };
            let ky_wrapped = if ky > L / 2 {
                ky as i32 - L as i32
            } else {
                ky as i32
            };
            let (wr, wi) = omega_hat[kx * L + ky];
            dwdx_hat[kx * L + ky] = (-(kx_wrapped as f64) * wi, (kx_wrapped as f64) * wr);
            dwdy_hat[kx * L + ky] = (-(ky_wrapped as f64) * wi, (ky_wrapped as f64) * wr);
        }
    }
    // Inverse transform to real space (with dealiasing on the inputs).
    let ux: Vec<f64> = idft2d(&ux_hat);
    let uy: Vec<f64> = idft2d(&uy_hat);
    let dwdx: Vec<f64> = idft2d(&dwdx_hat);
    let dwdy: Vec<f64> = idft2d(&dwdy_hat);
    // Multiply in real space, dealias the product in Fourier, return
    // the dealiased $\widehat{\vec u \cdot \nabla\omega}$.
    let mut product = vec![0.0; L * L];
    for i in 0..L * L {
        product[i] = ux[i] * dwdx[i] + uy[i] * dwdy[i];
    }
    let mut product_hat = dft2d(&product);
    for i in 0..L * L {
        if !mask[i] {
            product_hat[i] = (0.0, 0.0);
        }
    }
    product_hat
}

/// Compute the RHS of the vorticity equation in Fourier space:
///   $\mathrm{RHS} = -\widehat{\vec u \cdot \nabla\omega} - \nu k^2 \hat\omega + \hat f$.
fn rhs_hat(
    omega_hat: &[(f64, f64)],
    ksq: &[f64],
    f_hat: &[(f64, f64)],
    mask: &[bool],
) -> Vec<(f64, f64)> {
    let nl_hat = nonlinear_term_hat(omega_hat, ksq, mask);
    let mut out = vec![(0.0, 0.0); L * L];
    for i in 0..L * L {
        let (wr, wi) = omega_hat[i];
        let (nr, ni) = nl_hat[i];
        let (fr, fi) = f_hat[i];
        // Apply mask to ensure all terms share the same dealiased support.
        let m = if mask[i] { 1.0 } else { 0.0 };
        out[i] = (
            m * (-nr - NU * ksq[i] * wr + fr),
            m * (-ni - NU * ksq[i] * wi + fi),
        );
    }
    out
}

/// Advance the vorticity field by one RK4 step.
fn rk4_step(omega_hat: &mut [(f64, f64)], ksq: &[f64], f_hat: &[(f64, f64)], mask: &[bool]) {
    let k1 = rhs_hat(omega_hat, ksq, f_hat, mask);
    let omega2: Vec<(f64, f64)> = omega_hat
        .iter()
        .zip(k1.iter())
        .map(|(&(wr, wi), &(kr, ki))| (wr + 0.5 * DT * kr, wi + 0.5 * DT * ki))
        .collect();
    let k2 = rhs_hat(&omega2, ksq, f_hat, mask);
    let omega3: Vec<(f64, f64)> = omega_hat
        .iter()
        .zip(k2.iter())
        .map(|(&(wr, wi), &(kr, ki))| (wr + 0.5 * DT * kr, wi + 0.5 * DT * ki))
        .collect();
    let k3 = rhs_hat(&omega3, ksq, f_hat, mask);
    let omega4: Vec<(f64, f64)> = omega_hat
        .iter()
        .zip(k3.iter())
        .map(|(&(wr, wi), &(kr, ki))| (wr + DT * kr, wi + DT * ki))
        .collect();
    let k4 = rhs_hat(&omega4, ksq, f_hat, mask);
    for i in 0..L * L {
        let (wr, wi) = omega_hat[i];
        let (k1r, k1i) = k1[i];
        let (k2r, k2i) = k2[i];
        let (k3r, k3i) = k3[i];
        let (k4r, k4i) = k4[i];
        omega_hat[i] = (
            wr + DT * (k1r + 2.0 * k2r + 2.0 * k3r + k4r) / 6.0,
            wi + DT * (k1i + 2.0 * k2i + 2.0 * k3i + k4i) / 6.0,
        );
    }
}

/// Initial vorticity: Gaussian random field in Fourier space (small,
/// smooth — gives a reasonable initial condition for the Kolmogorov
/// flow to develop structure from). The amplitude is tiny so the
/// dynamics are dominated by the forcing (not the initial noise) for
/// the test's short time horizon.
fn initial_vorticity_hat(seed: u64) -> Vec<(f64, f64)> {
    let mut rng = seed;
    let mut hat = vec![(0.0, 0.0); L * L];
    for entry in hat.iter_mut() {
        rng = splitmix64(rng);
        let re = ((rng as f64) / (u64::MAX as f64) - 0.5) * 0.1;
        rng = splitmix64(rng);
        let im = ((rng as f64) / (u64::MAX as f64) - 0.5) * 0.1;
        *entry = (re, im);
    }
    // Zero the k=0 mode (mean vorticity — irrelevant for incompressible flow).
    hat[0] = (0.0, 0.0);
    hat
}

/// Generate a time series of Kolmogorov-flow vorticity snapshots.
/// Returns `n_snapshots` real-space vorticity fields, each of length D,
/// captured every `snapshot_stride` time steps after a `burn_in` initial
/// spin-up.
fn generate_kolmogorov_snapshots(
    n_snapshots: usize,
    snapshot_stride: usize,
    burn_in: usize,
    seed: u64,
) -> Vec<Vec<f64>> {
    let ksq = k_squared();
    let mask = dealias_mask();
    let f_hat = kolmogorov_forcing_hat();
    let mut omega_hat = initial_vorticity_hat(seed);
    // Burn-in: spin up the flow.
    for _ in 0..burn_in {
        rk4_step(&mut omega_hat, &ksq, &f_hat, &mask);
    }
    // Collect snapshots.
    let mut snapshots = Vec::with_capacity(n_snapshots);
    for _ in 0..n_snapshots {
        for _ in 0..snapshot_stride {
            rk4_step(&mut omega_hat, &ksq, &f_hat, &mask);
        }
        let real_space = idft2d(&omega_hat);
        // Normalise to [0, 1] so the QFM-TSR pipeline sees the same
        // pixel range as the image fixtures (the actual QFM-TSR pipeline
        // is dimension-agnostic but the cosine-similarity baseline is
        // easier to interpret on [0, 1] data).
        let min_v = real_space.iter().cloned().fold(f64::INFINITY, f64::min);
        let max_v = real_space.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
        let range = (max_v - min_v).max(1e-12);
        let normalized: Vec<f64> = real_space.iter().map(|&x| (x - min_v) / range).collect();
        snapshots.push(normalized);
    }
    snapshots
}

// ── Pipeline helpers ───────────────────────────────────────────────────────

fn cosine_similarity(a: &[f64], b: &[f64]) -> f64 {
    let dot: f64 = a.iter().zip(b.iter()).map(|(x, y)| x * y).sum();
    let na: f64 = a.iter().map(|x| x * x).sum::<f64>().sqrt();
    let nb: f64 = b.iter().map(|x| x * x).sum::<f64>().sqrt();
    if na == 0.0 || nb == 0.0 {
        0.0
    } else {
        dot / (na * nb)
    }
}

fn cfd_pipeline(training: &[Vec<f64>], seed: u64) -> QfmPipeline {
    let d = training[0].len();
    let m = training.len();
    // Same rank-truncation setup as `ising2d_validation.rs`:
    //   K_2 = max(M, d) = 256 (so the P10.16.3 lossy path is forced,
    //   because M=64 < K_2=256),
    //   krylov_dim = 32, max_rank = 16.
    // This makes CFD a true cross-domain exercise of the rank-truncation
    // path (not the lossless K_2=M path).
    let k2 = m.max(d);
    let config = QfmConfig {
        k: 16,
        k2,
        krylov_dim: 32,
        seed,
        n_t_samples: 4,
        noise_dim: d,
        max_rank: Some(16),
    };
    QfmPipeline::compile(training, &config).expect("QFM compile on 2D Kolmogorov flow snapshots")
}

// ── Tests ──────────────────────────────────────────────────────────────────

#[test]
fn cfd_kolmogorov_qfm_pipeline_compiles() {
    // 64 training snapshots × 256 pixels (L=16 Kolmogorov flow).
    // 50-step burn-in (the flow needs ~30 steps at ν=0.05, L=16 to
    // develop the characteristic vortices from the random initial
    // condition; 50 is safely past the spin-up). snapshot_stride=20
    // gives a 64-snapshot trajectory over 1280 production steps,
    // well within the test time budget when using the FFT-based solver.
    let training = generate_kolmogorov_snapshots(64, 20, 50, 0xCF0D);
    assert_eq!(training.len(), 64);
    assert_eq!(training[0].len(), D);
    for &p in &training[0] {
        assert!(
            (0.0..=1.0).contains(&p),
            "pixel {p} out of [0,1] after normalisation"
        );
    }

    let pipeline = cfd_pipeline(&training, 42);
    assert_eq!(pipeline.raw_dim(), D);
    assert!(pipeline.rank() >= 1, "rank must be >= 1");
    assert!(
        pipeline.rank() <= 16,
        "rank must be <= max_rank=16 after truncation, got {}",
        pipeline.rank()
    );
    println!(
        "cfd_kolmogorov_compile: rank={}, K_2={}, d={}",
        pipeline.rank(),
        pipeline.k2_dim(),
        pipeline.raw_dim()
    );
}

#[test]
fn cfd_kolmogorov_qfm_generate_finite_and_correlated() {
    let training = generate_kolmogorov_snapshots(64, 20, 50, 0xCF0D);
    let pipeline = cfd_pipeline(&training, 42);

    // Evaluate on the first 8 training snapshots (8 different time
    // points in the Kolmogorov trajectory).
    let mut sims = Vec::new();
    for (i, query) in training.iter().take(8).enumerate() {
        let x_out = pipeline.generate(query).expect("generate");
        assert_eq!(x_out.len(), D, "output must be d=256");
        for &v in &x_out {
            assert!(v.is_finite(), "generate output must be finite, got {v}");
        }
        let nearest_sim = training
            .iter()
            .map(|t| cosine_similarity(&x_out, t))
            .fold(f64::NEG_INFINITY, f64::max);
        sims.push(nearest_sim);
        println!("cfd_kolmogorov_generate[{i}]: nearest cosine sim = {nearest_sim:.4}");
    }
    // The Kolmogorov trajectory is highly structured, so a
    // rank-truncated QFM-TSR should produce a generate output that
    // is positively correlated with the training set. We require
    // max sim > 0.1 and min sim > 0.
    let max_sim = sims.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    assert!(
        max_sim > 0.1,
        "expected at least one generate output correlated with the CFD training set, max sim = {max_sim:.4}"
    );
    let min_sim = sims.iter().cloned().fold(f64::INFINITY, f64::min);
    assert!(
        min_sim > 0.0,
        "expected all CFD generate outputs positively correlated with the training set, min sim = {min_sim:.4}"
    );
}

#[test]
fn cfd_kolmogorov_qfm_bayes_update_held_out() {
    let training = generate_kolmogorov_snapshots(64, 20, 50, 0xCF0D);
    // 8 held-out snapshots from a different initial-condition seed
    // (so they're a fresh trajectory, not just late-training-snapshots).
    let held_out = generate_kolmogorov_snapshots(8, 20, 50, 0xFEED);

    let pipeline = cfd_pipeline(&training, 42);
    let c_prior = tsr_evolved_prior(&pipeline);

    let opts = HmcOpts {
        leapfrog_steps: 20,
        step_size: 0.05,
        n_iterations: 50,
        burn_in: 25,
        seed: 42,
    };

    let mut overlaps = Vec::new();
    for (i, obs) in held_out.iter().enumerate() {
        let c_obs = match pipeline.encode(obs) {
            Ok(c) if c.iter().map(|x| x.norm_sqr()).sum::<f64>().sqrt() > 1e-6 => c,
            _ => {
                println!("cfd_kolmogorov_bayes[{i}]: c_obs zero (S_2 fallback); skipping");
                continue;
            }
        };
        let likelihood = Likelihood::from_observation(&pipeline, obs).expect("likelihood");
        let posterior = Posterior::new(vec![likelihood], c_prior.clone());
        let sample = sample_hmc_single(&posterior, &opts);
        let overlap: f64 = sample
            .iter()
            .zip(c_obs.iter())
            .map(|(a, b)| (a.conj() * b).re)
            .sum();
        let overlap_sq = overlap * overlap;
        println!("cfd_kolmogorov_bayes[{i}]: |<sample|c_obs>|² = {overlap_sq:.4}");
        overlaps.push(overlap_sq);
    }

    assert!(
        !overlaps.is_empty(),
        "expected at least one held-out CFD snapshot to have a non-zero c_obs"
    );
    let max_overlap = overlaps.iter().cloned().fold(0.0_f64, f64::max);
    assert!(
        max_overlap > 0.01,
        "expected at least one HMC sample to have non-trivial overlap with its observation, max = {max_overlap:.4}"
    );
}

#[test]
fn cfd_kolmogorov_qfm_no_explosion_on_held_out() {
    let training = generate_kolmogorov_snapshots(64, 20, 50, 0xCF0D);
    let held_out = generate_kolmogorov_snapshots(8, 20, 50, 0xFEED);
    let pipeline = cfd_pipeline(&training, 42);

    for (i, obs) in held_out.iter().enumerate() {
        let x_out = pipeline.generate(obs).expect("generate held-out");
        for &v in &x_out {
            assert!(
                v.is_finite(),
                "held-out generate output must be finite, got {v} (idx={i})"
            );
        }
    }
}
