//! P10.16.2: Real-data validation of the QFM-TSR pipeline on CIFAR-10 16×16.
//!
//! This test uses a real CIFAR-10 fixture generated by
//! `qfm/scripts/make_cifar10_fixture.py` (ITU-R 601 grayscale + 2×2 block
//! average, 32×32 → 16×16 = d=256). The fixture selects:
//!   - 256 training images (8 classes × 32 images/class) from data_batch_1.bin
//!   - 8 held-out images (1 per class) from test_batch.bin
//!
//! What the test verifies:
//!   1. QFM-TSR pipeline compiles on real d=256 CIFAR-10 images.
//!   2. `generate()` on a training point returns finite pixel values.
//!   3. Cosine similarity to the nearest training point is positive.
//!   4. The Quantum Bayesian Update on a held-out observation runs
//!      end-to-end and produces a finite decoded image.
//!   5. The HMC posterior sample's Born-rule overlap with the
//!      observation's Krylov state is positive.
//!
//! The fixture files are produced by running:
//!   cd unfer && python3 qfm/scripts/make_cifar10_fixture.py
//!
//! Pipeline config: k=16 (16:1 sketch compression), K_2=256 (= max(M, d)),
//! krylov_dim=256.  Comparable ratio to the MNIST 8×8 test (k=4, K_2=65).

use qfm::{
    HmcOpts, Likelihood, Posterior, QfmConfig, QfmPipeline, sample_hmc_single, tsr_evolved_prior,
};

#[derive(serde::Deserialize)]
struct CifarSample {
    label: u32,
    pixels: Vec<f64>,
}

fn load(path: &str) -> Vec<Vec<f64>> {
    let data = std::fs::read_to_string(path).expect("read cifar json");
    let samples: Vec<CifarSample> = serde_json::from_str(&data).expect("parse cifar json");
    samples.into_iter().map(|s| s.pixels).collect()
}

fn load_with_labels(path: &str) -> Vec<(u32, Vec<f64>)> {
    let data = std::fs::read_to_string(path).expect("read cifar json");
    let samples: Vec<CifarSample> = serde_json::from_str(&data).expect("parse cifar json");
    samples.into_iter().map(|s| (s.label, s.pixels)).collect()
}

fn cosine_similarity(a: &[f64], b: &[f64]) -> f64 {
    let dot: f64 = a.iter().zip(b.iter()).map(|(x, y)| x * y).sum();
    let na: f64 = a.iter().map(|x| x * x).sum::<f64>().sqrt();
    let nb: f64 = b.iter().map(|x| x * x).sum::<f64>().sqrt();
    if na == 0.0 || nb == 0.0 {
        0.0
    } else {
        dot / (na * nb)
    }
}

fn pipeline_for(training: &[Vec<f64>], seed: u64) -> QfmPipeline {
    let d = training[0].len(); // 256 (16×16 CIFAR-10 grayscale)
    let m = training.len();    // 256 (8 classes × 32)
    let k2 = m.max(d);         // 256 = max(256, 256)
    let config = QfmConfig {
        k: 16,
        k2,
        krylov_dim: k2,
        seed,
        n_t_samples: 4,
        noise_dim: d,
        max_rank: None,
    };
    QfmPipeline::compile(training, &config).expect("QFM compile on real CIFAR-10")
}

#[test]
fn cifar10_real_qfm_pipeline_compiles() {
    let training: Vec<Vec<f64>> = load("testdata/cifar10_16x16_256training.json");
    assert_eq!(training.len(), 256, "expected 256 training images (8 × 32)");
    assert_eq!(training[0].len(), 256, "expected d=256 (16×16 grayscale)");
    // All pixels must be in [0, 1] (the fixture normalises them).
    for &px in &training[0] {
        assert!(
            (0.0..=1.0).contains(&px),
            "pixel value {px} out of [0, 1]"
        );
    }

    let pipeline = pipeline_for(&training, 42);
    assert_eq!(pipeline.raw_dim(), 256, "raw dim must be 256");
    assert_eq!(pipeline.k2_dim(), 256, "K_2 must be 256 = max(m, d)");
    assert!(pipeline.rank() >= 1, "rank must be >= 1");
    println!(
        "cifar10_real_compile: rank = {}, K_2 = {}",
        pipeline.rank(),
        pipeline.k2_dim()
    );
}

#[test]
fn cifar10_real_qfm_generate_finite_and_correlated() {
    let training: Vec<Vec<f64>> = load("testdata/cifar10_16x16_256training.json");
    let pipeline = pipeline_for(&training, 42);

    // Sample 8 representative queries (one per class, first image of each).
    let queries: Vec<&Vec<f64>> = (0..8).map(|c| &training[c * 32]).collect();
    let mut sims = Vec::new();
    for (i, query) in queries.iter().enumerate() {
        let x_out = pipeline.generate(query).expect("generate");
        assert_eq!(x_out.len(), 256);
        for &v in &x_out {
            assert!(v.is_finite(), "generate output must be finite, got {v}");
        }
        let nearest_sim = training
            .iter()
            .map(|t| cosine_similarity(&x_out, t))
            .fold(f64::NEG_INFINITY, f64::max);
        sims.push(nearest_sim);
        println!(
            "cifar10_real_generate[class {i}]: nearest cosine sim = {nearest_sim:.4}"
        );
    }
    let max_sim = sims.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    assert!(
        max_sim > 0.2,
        "expected at least one generate output to be correlated with the training set, max sim = {max_sim:.4}"
    );
    let min_sim = sims.iter().cloned().fold(f64::INFINITY, f64::min);
    assert!(
        min_sim > 0.0,
        "expected all class-representative generate outputs to be positively correlated, min sim = {min_sim:.4}"
    );
}

#[test]
fn cifar10_real_qfm_bayes_update_recovers_held_out_observation() {
    let training: Vec<Vec<f64>> = load("testdata/cifar10_16x16_256training.json");
    let held_out: Vec<(u32, Vec<f64>)> =
        load_with_labels("testdata/cifar10_16x16_8heldout.json");
    assert_eq!(held_out.len(), 8, "expected 8 held-out images (1 per class)");

    let pipeline = pipeline_for(&training, 42);
    let c_prior = tsr_evolved_prior(&pipeline);

    let opts = HmcOpts {
        leapfrog_steps: 20,
        step_size: 0.05,
        n_iterations: 50,
        burn_in: 25,
        seed: 42,
    };

    let mut overlaps = Vec::new();
    for (i, (label, obs)) in held_out.iter().enumerate() {
        let c_obs = match pipeline.encode(obs) {
            Ok(c) if c.iter().map(|x| x.norm_sqr()).sum::<f64>().sqrt() > 1e-6 => c,
            _ => {
                println!(
                    "cifar10_real_bayes_update[{i}]: label = {label}, c_obs is zero (S_2 fallback); skipping"
                );
                continue;
            }
        };
        let likelihood = Likelihood::from_observation(&pipeline, obs).expect("likelihood");
        let posterior = Posterior::new(vec![likelihood], c_prior.clone());
        let sample = sample_hmc_single(&posterior, &opts);
        let overlap: f64 = sample
            .iter()
            .zip(c_obs.iter())
            .map(|(a, b)| (a.conj() * b).re)
            .sum();
        let overlap_sq = overlap * overlap;
        println!(
            "cifar10_real_bayes_update[{i}]: label = {label}, |<sample|c_obs>|² = {overlap_sq:.4}"
        );
        overlaps.push(overlap_sq);
    }

    assert!(
        !overlaps.is_empty(),
        "expected at least one held-out image to have a non-zero c_obs"
    );
    let max_overlap = overlaps.iter().cloned().fold(0.0_f64, f64::max);
    assert!(
        max_overlap > 0.01,
        "expected at least one HMC sample to have non-trivial overlap with its observation, max |<sample|c_obs>|² = {max_overlap:.4}"
    );
}

#[test]
fn cifar10_real_qfm_no_explosion_on_held_out() {
    let training: Vec<Vec<f64>> = load("testdata/cifar10_16x16_256training.json");
    let held_out: Vec<(u32, Vec<f64>)> =
        load_with_labels("testdata/cifar10_16x16_8heldout.json");

    let pipeline = pipeline_for(&training, 42);

    for (i, (label, obs)) in held_out.iter().enumerate() {
        let x_out = pipeline.generate(obs).expect("generate held-out");
        for &v in &x_out {
            assert!(
                v.is_finite(),
                "held-out generate output must be finite, got {v} (label = {label}, idx = {i})"
            );
        }
    }
}
