"""Emit the const list for `codes.rs`'s coverage test.

Rust cannot reflect over associated consts, so the test needs an explicit
list to compare `all()` against. This script derives that list from the
source, so regenerating after adding a code is one command rather than 114
hand-typed lines.

    nix-shell -p python3 --run "python3 scripts/gen_code_consts.py"
"""

import io
import re
import sys

SRC = "unfer_protocol/src/codes.rs"
OUT = "unfer_protocol/src/codes_consts.rs"

text = io.open(SRC, encoding="utf-8").read()

# `pub const NAME: Code = Code(1234);` — only the constants, not interior uses.
pairs = re.findall(r"pub const ([A-Z0-9_]+): Code = Code\((\d+)\);", text)
if not pairs:
    sys.exit("no constants found; did the declaration syntax change?")

nums = [int(n) for _, n in pairs]
dupes = {n for n in nums if nums.count(n) > 1}
if dupes:
    sys.exit("duplicate code numbers among the constants: %s" % sorted(dupes))

names = [n for n, _ in pairs]
dupe_names = {n for n in names if names.count(n) > 1}
if dupe_names:
    sys.exit("duplicate constant names: %s" % sorted(dupe_names))

# How many rows does the table actually carry? Reported so a mismatch between
# this file and `all()` is visible at generation time, not only in the test.
start = text.find("pub fn all()")
end = text.find("\n}", start) if start >= 0 else -1
section = text[start:end] if start >= 0 and end > start else ""
rows = re.findall(r"^\s+(\d{4}),\s*$", section, re.M)
if len(rows) != len(pairs):
    print(
        "warning: %d constants but all() has %d rows -- the coverage test will "
        "fail until all() is updated" % (len(pairs), len(rows)),
        file=sys.stderr,
    )

body = ",\n".join('    ("%s", %s)' % (name, num) for name, num in pairs)

out = '''//! Generated by `scripts/gen_code_consts.py` -- do not edit by hand.
//!
//! `%d` constants paired with their numbers, so `codes.rs`'s test can assert
//! that the hand-maintained `all()` table carries a row for every one of them.
//! The two are separate lists on purpose (a macro would fuse them, at the cost
//! of rewriting %d declarations in a file every crate depends on), so the
//! divergence is caught by a test instead of by a consumer discovering that
//! `name_of` returns `None` for a real error.
//!
//! Regenerate after adding or renumbering a code:
//!
//! ```sh
//! nix-shell -p python3 --run "python3 scripts/gen_code_consts.py"
//! ```

/// `(constant name, code number)` for every `Code` associated constant.
pub const CONSTS: &[(&str, u32)] = &[
%s,
];
''' % (len(pairs), len(pairs), body)

io.open(OUT, "w", encoding="utf-8").write(out)
print("wrote %s with %d constants (all() has %d rows)" % (OUT, len(pairs), len(rows)))
if len(rows) != len(pairs):
    sys.exit(1)