-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lib]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace sirk_core_model

/-- [std::f64::{f64}::sqrt]:
    Source: '/rustc/library/std/src/num/f64.rs', lines 386:4-386:28
    Name pattern: [std::f64::{f64}::sqrt]
    Visibility: public -/
@[rust_fun "std::f64::{f64}::sqrt"] axiom std.f64.F64.sqrt : F64 → Result F64

/-- [lib::C64]
    Source: 'src/lib.rs', lines 34:0-37:1
    Visibility: public -/
structure C64 where
  re : F64
  im : F64

/-- [lib::{lib::C64}::new]:
    Source: 'src/lib.rs', lines 40:4-42:5
    Visibility: public -/
def C64.new (re : F64) (im : F64) : Result C64 := do
  ok { re, im }

/-- [lib::{lib::C64}::conj]:
    Source: 'src/lib.rs', lines 47:4-52:5
    Visibility: public -/
def C64.conj (self : C64) : Result C64 := do
  sorry

/-- [lib::{impl core::clone::Clone for lib::C64}::clone]:
    Source: 'src/lib.rs', lines 56:4-61:5
    Visibility: public -/
def C64.Insts.CoreCloneClone.clone (self : C64) : Result C64 := do
  ok self

/-- Trait implementation: [lib::{impl core::clone::Clone for lib::C64}]
    Source: 'src/lib.rs', lines 55:0-62:1 -/
@[reducible]
def C64.Insts.CoreCloneClone : core.clone.Clone C64 := {
  clone := C64.Insts.CoreCloneClone.clone
}

/-- [lib::forward_step]:
    Source: 'src/lib.rs', lines 79:0-102:1
    Visibility: public -/
def forward_step
  (h : Slice C64) (w : Slice C64) (z : C64) (dim : Std.Usize) :
  Result (alloc.vec.Vec C64)
  := do
  sorry

/-- [lib::forward_sequence]: loop body 0:
    Source: 'src/lib.rs', lines 117:4-123:5
    Visibility: public -/
@[rust_loop_body]
def forward_sequence_loop0.body
  (v0 : Slice C64) (dim : Std.Usize) (v : alloc.vec.Vec C64) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec C64) × Std.Usize) (alloc.vec.Vec C64))
  := do
  if i < dim
  then
    let c ← Slice.index_usize v0 i
    let v1 ← alloc.vec.Vec.push v { c with im := c.im }
    let i1 ← i + 1#usize
    ok (cont (v1, i1))
  else ok (done v)

/-- [lib::forward_sequence]: loop 0:
    Source: 'src/lib.rs', lines 117:4-123:5
    Visibility: public -/
@[rust_loop]
def forward_sequence_loop0
  (v0 : Slice C64) (dim : Std.Usize) (v : alloc.vec.Vec C64) (i : Std.Usize) :
  Result (alloc.vec.Vec C64)
  := do
  loop
    (fun (v1, i1) => forward_sequence_loop0.body v0 dim v1 i1)
    (v, i)

/-- [lib::forward_sequence]: loop body 1:
    Source: 'src/lib.rs', lines 126:4-131:5
    Visibility: public -/
@[rust_loop_body]
def forward_sequence_loop1.body
  (h : Slice C64) (z : Slice C64) (m : Std.Usize) (dim : Std.Usize)
  (ws : alloc.vec.Vec (alloc.vec.Vec C64)) (k : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec (alloc.vec.Vec C64)) × Std.Usize)
    (alloc.vec.Vec (alloc.vec.Vec C64)))
  := do
  if k < m
  then
    let prev ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (alloc.vec.Vec
        C64)) ws k
    let s := alloc.vec.Vec.deref prev
    let c ← Slice.index_usize z k
    let next ← forward_step h s c dim
    let ws1 ← alloc.vec.Vec.push ws next
    let k1 ← k + 1#usize
    ok (cont (ws1, k1))
  else ok (done ws)

/-- [lib::forward_sequence]: loop 1:
    Source: 'src/lib.rs', lines 126:4-131:5
    Visibility: public -/
@[rust_loop]
def forward_sequence_loop1
  (h : Slice C64) (z : Slice C64) (m : Std.Usize) (dim : Std.Usize)
  (ws : alloc.vec.Vec (alloc.vec.Vec C64)) (k : Std.Usize) :
  Result (alloc.vec.Vec (alloc.vec.Vec C64))
  := do
  loop
    (fun (ws1, k1) => forward_sequence_loop1.body h z m dim ws1 k1)
    (ws, k)

/-- [lib::forward_sequence]:
    Source: 'src/lib.rs', lines 113:0-133:1
    Visibility: public -/
def forward_sequence
  (h : Slice C64) (v0 : Slice C64) (z : Slice C64) (m : Std.Usize)
  (dim : Std.Usize) :
  Result (alloc.vec.Vec (alloc.vec.Vec C64))
  := do
  let i ← m + 1#usize
  let ws := alloc.vec.Vec.with_capacity (alloc.vec.Vec C64) i
  let v := alloc.vec.Vec.with_capacity C64 dim
  let v1 ← forward_sequence_loop0 v0 dim v 0#usize
  let ws1 ← alloc.vec.Vec.push ws v1
  forward_sequence_loop1 h z m dim ws1 0#usize

/-- [lib::gram_entry]:
    Source: 'src/lib.rs', lines 140:0-158:1
    Visibility: public -/
def gram_entry
  (wj : Slice C64) (wk : Slice C64) (dim : Std.Usize) : Result C64 := do
  sorry

/-- [lib::gram_assembly]: loop body 0:
    Source: 'src/lib.rs', lines 170:4-181:5
    Visibility: public -/
@[rust_loop_body]
def gram_assembly_loop.body
  (ws : Slice (alloc.vec.Vec C64)) (dim : Std.Usize) (n : Std.Usize)
  (g : alloc.vec.Vec C64) (t : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec C64) × Std.Usize) (alloc.vec.Vec C64))
  := do
  let i ← n * n
  if t < i
  then
    let j ← t / n
    let k ← t % n
    let wj ← Slice.index_usize ws j
    let wk ← Slice.index_usize ws k
    let s := alloc.vec.Vec.deref wj
    let s1 := alloc.vec.Vec.deref wk
    let e ← gram_entry s s1 dim
    let g1 ← alloc.vec.Vec.push g e
    let t1 ← t + 1#usize
    ok (cont (g1, t1))
  else ok (done g)

/-- [lib::gram_assembly]: loop 0:
    Source: 'src/lib.rs', lines 170:4-181:5
    Visibility: public -/
@[rust_loop]
def gram_assembly_loop
  (ws : Slice (alloc.vec.Vec C64)) (dim : Std.Usize) (n : Std.Usize)
  (g : alloc.vec.Vec C64) (t : Std.Usize) :
  Result (alloc.vec.Vec C64)
  := do
  loop
    (fun (g1, t1) => gram_assembly_loop.body ws dim n g1 t1)
    (g, t)

/-- [lib::gram_assembly]:
    Source: 'src/lib.rs', lines 166:0-183:1
    Visibility: public -/
def gram_assembly
  (ws : Slice (alloc.vec.Vec C64)) (m : Std.Usize) (dim : Std.Usize) :
  Result (alloc.vec.Vec C64)
  := do
  let n ← m + 1#usize
  let i ← n * n
  let g := alloc.vec.Vec.with_capacity C64 i
  gram_assembly_loop ws dim n g 0#usize

/-- [lib::projection_identity]:
    Source: 'src/lib.rs', lines 197:0-202:1
    Visibility: public -/
def projection_identity
  (g_j_kp1 : C64) (g_j_k : C64) (scale_kp1 : F64) (z_k : C64) :
  Result C64
  := do
  sorry

/-- [lib::whitening_transform]:
    Source: 'src/lib.rs', lines 217:0-240:1
    Visibility: public -/
def whitening_transform
  (eigvals : Slice F64) (eigvecs : Slice C64) (n : Std.Usize)
  (rank : Std.Usize) :
  Result (alloc.vec.Vec C64)
  := do
  sorry

/-- [lib::residual_boundary_component]:
    Source: 'src/lib.rs', lines 256:0-261:1
    Visibility: public -/
def residual_boundary_component
  (c_hat_last : C64) (scale_m : F64) : Result C64 := do
  sorry

/-- [lib::residual_norm2]:
    Source: 'src/lib.rs', lines 268:0-289:1
    Visibility: public -/
def residual_norm2
  (e : Slice C64) (g : Slice C64) (m : Std.Usize) : Result F64 := do
  sorry

end sirk_core_model
